### ISSUE TITLE
Nice - support for more than one device possible?

### ISSUE THREAD

**Issue by MacSass** [Aircoookie/Espalexa#1]
Hi Aircookie,
this is great and works perfect for me - I like the feature of being able to respond to a "dimming" value a lot.

Only thing I´m currently missing is the support for more then one device - right now I have no real clue I to add that.
Would you be able to provide an extension to more than one device?

Thanks for your work - MacSass

**Comment by Aircoookie** [comment]
Hi MacSass,
sure, that should be quite a simple addition. I'm sure I can extend the sketch so you can dynamically use up to 16 devices. I'll get back to you when it's ready, should be done within a maximum of 3 days though! Later I will also add ESP32 support and make the whole thing an Arduino library for easier integration, but that'll take a while since I never did that before.

Perfect that it work for you and you like it, that is very encouraging :)

**Comment by MacSass** [comment]
Hi Aircookie,
sounds great - perfect, I´m looking forward to it, but take your time - no rush.
Would be nice if devices could be added fairly easy, if you are not aware, maybe take a look at
https://github.com/kakopappa/arduino-esp8266-alexa-multiple-wemo-switch
it emulates a wemo switch (which makes it more limited than your hue emulation) but it is fairly easy to add more devices (just some definitions and of course the respective call-backs).

Thanks for your work - MacSass

**Comment by Aircoookie** [comment]
And... it's done already! Multiple device support and ESP32 support is in the latest commit! Just change the  define DEVICES in line 24 and add/remove name and initial state array entries from line 84.

Also I'm already planning on making this a library, which will make it much easier to add devices and integrate it into your projects.

Thank you so much for your support of the project!

**Comment by MacSass** [comment]
Wow,
great - I give it a try during the next days and report back. Might take longer though than it took you to get it implemented :-)

Thanks - MacSass

**Comment by MacSass** [comment]
HI Aircookie,
I finally came around to do some testing. 
First of all: Discovery is working great - all devices found right away as dimmable lights. Adding / Removing lights seems easy enough as well.

I´m experiencing some issues with switching / dimming though that I have not been able to figure out:

1.) When switching/dimming a device, I see for each single switch a total of 3 error messages in the serial monitor:

> IP address: 192.168.1.30
Ask Alexa to discover devices
Con UDP
Con success
HTTP Server started ..
Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights/1
Body: 
AlexaApiCall
ok
l1
Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights/1/state
Body: {"on":true}
AlexaApiCall
ok
ls1
Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights/1
Body: 
AlexaApiCall
ok
l1

I´m not sure if this is OK or not ... but switching and dimming is working as it should.

Also, about every second I do see a:

> 192.168.1.1, port 33191

Which is the IP of my router. Could it be the router is doing broadcasts every seconds that the ESP logs? Could be OK as well ... does not seem to cause issues.

Finally a real issue:
After a couple of minutes I suddenly see the serial monitor being spammed with "Cannot connect to Wifi" - although it was connected OK before - not sure what is happing. Here is the output:

> Not-Found HTTP call:
URI: /api/2WLEDHardQrI3WHYTHoMcXHgEspsM8ZZRpSKtBQr/lights/3
Body: 
AlexaApiCall
ok
l3
192.168.1.1, port 33191
192.168.1.1, port 33191
192.168.1.1, port 1900
Cannot connect to Wifi
Cannot connect to Wifi
Cannot connect to Wifi
Cannot connect to Wifi
.......

This goes on forever and fills the serial monitor with high speed. 
Funny enough: The device continues to work! Just it floods the serial monitor with "Cannot connect to Wifi" until the IDE crashes.
Looks like the last entry before the crash always is the port 1900:

> 192.168.1.1, port 33191
192.168.1.1, port 33191
192.168.1.1, port 1900
Cannot connect to Wifi
Cannot connect to Wifi
.....

Let me know if I can help with getting this fixed.

Thanks for your work - MacSass

**Comment by Aircoookie** [comment]
Hi MacSass,

thank you so much for your extensive testing. Great that the discovery works without problems!

The first log you posted suggest everything works flawlessly. Perhaps you may have though it's an error because of the "Not-Found HTTP call", but that only means that the control request by Alexa is not a valid HTML page on the ESPs internal server (of course). The next few lines
> Body: {"on":true}
> AlexaApiCall
> ok
> ls1
mean that it is in fact a successful control request.

If you see an IP (of your e.g your router) with a port that means that device has send a device discovery request the ESP received. It has however also detected that that discovery request was for a different kind of device. If it was a Hue device discovery request (like Alexa sends) you'll also see something like "Send resp to..." in the serial console.

After trying this for a few minutes, I also get the "Cannot connect to Wifi" serial message loops. Since the service still works however, there must be something that sets the "wifiConnected" boolean variable to "false" even though Wifi is still working. However, no part of the code does that, which confuses me. Therefore, I have just removed the check if the Wifi is still connected in the latest commit, because if it isn't anymore, nothing would work anyways.

By the way, a significant part of the upcoming library is already done, but there is still a lot of work to be done to get it as convenient to use as possible. Stay tuned!

Hope this works nicely for you! 
-Aircoookie

**Comment by Aircoookie** [comment]
Thank you for spreading the word! :) 

Your point about doing the "wifiConnected" check in setup is valid, I was falsely assuming that the method connectWifi() would stay in a loop forever until it is connected, but it cancels after 5sec. For the library, this will not be relevant, thankfully, since the main sketch will handle connecting to WiFi and the library will just check it seperately.

Have a nice weekend! -Air

**Comment by f1andy** [comment]
I know this page was last updated 5 years ago, But the connected flag might be being reset in fauxmoESP.cpp, in the  _onTCPData() function.  The data has a 0 added at the end to mark end of string for printing, but I think it is writing to one memory location after the end of the string.  If this happened to be where WiFi state was stored, it would clear the flag..
	
"p[len] = 0; "
