### ISSUE TITLE
What about COLORS support ? That could be really cool...

### ISSUE THREAD

**Issue by MopheusDG** [Aircoookie/Espalexa#12]
Hi, SORRY... me again, got very excited with this library :+1: 

What about adding HUE color support ? So that we could get a "Alexa, set Desk Light to Red" ? Possible ?

Thanks again.

**Comment by Aircoookie** [comment]
No problem, feel free to open issues! It helps the project :)

I'd LOVE to do that, sadly it is not supported by the Echo. I don't know why exactly, since the protocol is based on the Hue local API, which supports this. I even defined the light type as "Extended color light", still the Echo tells me "That is not supported by this device". It's probably so that people are forced to use the Philips cloud solution for their official hue lamps, which as a side effect makes color support impossible for projects that emulate the local API like Espalexa.

So sorry I can't add color support, but at least it's not my own fault :D

**Comment by MopheusDG** [comment]
No worries, it's still an amazing library. Just one question, I'm gonna take a look at your WLED project later today because that one seems to be amazing too and I'm looking forward to check (need to read again the project page cause I don't know what code to use on the ESP, but will check again later). Now my question is, if HUE is being emulated, do HUE color lamps don't support asking Alexa for an specific color ? I can't check it cause I only have 2 white HUE lamps, and they are hard to get an expensive in Argentina to buy, so I'm waiting for someone from Spain to get me a color one.

**Comment by Aircoookie** [comment]
If you connect a hue bridge with some HUE color lamps with Alexa via your Philips hue account, yes you can control their color. Great that you want to give WLED a try! In fact it's my main project and I developed Espalexa specifically for it, but thought it was so useful I'd release it as a stand-alone library. Feel free to ask me any questions if you need help setting it up! When you got a Hue color light connected to the Hue bridge, you can connect WLED to it. The WLED light doesn't work as an individually controllable light, however what it can do is "clone" the color of your Hue light.

By the way, the hue Bridge can remember official Hue lights, that means if you can borrow a color lamp from someone you can set it up with WLED and then give it back. The hue Bridge will still remember the Hue light and set the WLED light to the color you set via Alexa or the hue App. However, if you can afford keeping the hue color bulb, I definiately recommend doing so, because they are awesome!

**Comment by MopheusDG** [comment]
Thanks ! Will close this one as the app is working amazingly well so far. I'm actually using the Dimmer funtion to shoot diferent things via Alexa, for example, I have a TV device en ESPAlexa, when you say TURN ON TV launches a command, and if you say SET TV TO 1 it switches video inputs, and then, with a ROUTINE, I renamed it to SWITCH TV TO HDMI (That actually starts the TV "lamp" on 1%)... and works amazingly well.... I used to for my led colors too, via routines.

That way only with 10 devices, I can control almost 25 or 30 "things", cause my ESP has LED's and also an IR Led to control my AC (And now I can say.. Alexa, Set my AC to 24 and works AMAZINGLY well) !

So thanks.... amazing library, hope this is useful for other ppl too.

**Comment by MopheusDG** [comment]
Sorry about the confusing explain, can clarify if needed:

"Alexa, turn on air conditioner" = IR command to turn on AC
"Alexa, set air confitioner to 24" = IR command using dimmer value 24%
"Alexa, switch TV to HDMI" is a Routine, that launches Turns ON TV with value 1%, for example, and my .ino uses that brightness value to launch something different, an IR command that push HDMI button.

Hope this help somebody crazy as me :)

**Comment by Aircoookie** [comment]
That's awesome! Great it's working that well for you!
