### ISSUE TITLE
2 ESP's on same network = conflict ?

### ISSUE THREAD

**Issue by MopheusDG** [Aircoookie/Espalexa#15]
Hi, I've installed your library on 2 ESP's at the same time and Alexa discovers one perfectly fine, but when I turn the second ESP on, the devices are being renamed with the new ESP devices, instead of adding them as new one's.

An example:

ESP #1: Dev0 = TV
ESP #2: Dev0 = Amplifier

Alexa will discover TV first, and when I turn on the ESP #2, it will replace TV with Amplifier.

I think this is related with the devices ID's, any easy way to fix it ? Or should I use DEV0, DEV1 in ESP #1 and DEV 2, DEV3 in ESP #2 and that's the only way.

By the way, this does not happen on the FauxmoESP library, each device is related to the IP I think, so you can have 2 or 3 ESP's without issues of conflicting.

Thanks !!!!

**Comment by Aircoookie** [comment]
Hi,

that shouldn't happen.
I've got several ESPs running and they are all detected as separate devices.
The Echo distincts the devices via their MAC address (or possibly the IP). I cannot imagine your two ESPs having the same MAC, but you could check that with your router.

Using "throwaway" devices DEV0 and DEV1 in ESP 1 would help, but it doesn't solve the root of the issue. I'll try if I can reproduce it with 2 ESPs on the weekend :)

**Comment by MopheusDG** [comment]
It is weird.... maybe cause I'm using fixed IP's on the ESP's ? More weird is that I can see both via IP just fine:

**ESP #1 - IP 30** 
Hello from Espalexa!

Value of device 1 (tv): 0
Value of device 2 (tv sound): 0
Value of device 3 (tv mute): 0
Value of device 4 (Sony): 13
Value of device 5 (Sony sound): 0
Value of device 6 (Sony mute): 0
Value of device 7 (Sony next): 0
Value of device 8 (Sony soundfield): 0
Value of device 9 (air conditioner): 0
Value of device 10 (air conditioner spin): 0
Value of device 11 (air conditioner ventilation): 0
Value of device 12 (external light): 0
Value of device 13 (external light fading): 0

Free Heap: 36784
Uptime: 243468479

Espalexa library V2.1.0 by Christian Schwinne 2018

**ESP #2 - IP 31**
Hello from Espalexa!

Value of device 1 (projector): 0
Value of device 2 (projector sound): 0
Value of device 3 (projector mute): 0
Value of device 4 (projector input): 0
Value of device 5 (projector usb): 0
Value of device 6 (projector freeze): 0
Value of device 7 (tv channel): 0
Value of device 8 (tv third dimension): 0
Value of device 9 (tv info): 0
Value of device 10 (tv tools): 0
Value of device 11 (my display): 0
Value of device 12 (my display color): 0
Value of device 13 (my display effect): 0

Free Heap: 38168
Uptime: 119746

Espalexa library V2.1.0 by Christian Schwinne 2018

**Comment by Aircoookie** [comment]
There's absolutely nothing wrong with using fixed IPs!
I hope I'll be able to reproduce and fix the issue. 
A lot of "devices" you've got there! Clever idea to use it as a full-blown remote control :)

Just for the record. For the devices to get renamed it is enough to turn the 2nd ESP on, correct? Or does it only happen if you let the Echo search for devices?

Thanks for helping me solve this!

**Comment by MopheusDG** [comment]
Mmmm... no sure, I think I need to do a search via Alexa, but I'm not sure, usually when I started the ESP #2 I've always run a search to see if it works. I can try not discovering but will that work ?

**Comment by MopheusDG** [comment]
Still couldn't figure this out... ESP01 is my remote #1, Wemos D1 Min is my #2 remote, both quite diferents, diferent Mac's of course, still ... they overlap for some reason. Maybe Amazon changed something on the way it associates the strips with the devices ?

**Comment by Aircoookie** [comment]
Hi again,

I did some testing myself and could reproduce the issue. I took 2 Wemos D1 mini on static IPs 10.10.1.30 and 10.10.1.31 and configured the devices Alpha 1-5 and Beta 1-5 there. On the first try only Beta 1-5 showed up, after deleting them and retrying I had the devices Alpha 1, Alpha 2, Beta 3, Alpha 4, and Beta 5. It seems like the way the Echo saves those devices is quite unreliable or random... Next try I had every device show up except Alpha 1. Then finally I had all devices work. So you can work-around the issue by doing device-discovery (best via the Alexa app) multiple times. Also you can try deleting the found devices and then discovering again. Finally, you could unplug one ESP and see if Alexa finds the devices of the other. A combination of these things should help you get all devices working, mostly doing discovery over and over again.

I still don't know why this even happens, since my ESPs definitely have different MAC addresses so every virtual device has a different unique ID. Perhaps it's a bug in the Echo discovery code (there are some, for sure) or it's my fault, but I just don't see where yet. Interestingly, I also had an ESP32 on 10.10.1.32 emulating the devices Casper 1-5 and those devices always showed up and never interfered with the Wemos D1 devices. This surely is a strange issue, but I'll continue to monitor it further.

**Comment by MopheusDG** [comment]
Hi Aircookie, thanks for the follow up. I don't have your luck, everytime I want to discover devices via Alexa app, it's replacing my old one's... if I discover with ESP 1 only, I got all devices perfect, if I power down ESP 1 and turn on ESP 2, when I discover, I just get the new one's replacing the old one's....
Hope you can find the problem, I was really in love with your library, it's really useful not like FauxoESP that is too limited in values you can receive.

By the way, when I was taking a look at the HUE-Emulator library, I think that their library has this problem, cause you can't have more than one HUE Bridge emulator, at least that's what I remember reading over there... maybe that's what it's affecting your library too ? ESPAlexa is based on both projects, right ? FauxmoESP and Hue-Emulator together... am I right ?

**Comment by Aircoookie** [comment]
That's a bummer! Did you also try deleting the discovered devices in the Alexa app? The last thing i could think about is to try a different ESP or different fixed IP addresses...

On an unrelated note, do you use 2 ESPs because the devices you control are not close to another or just because you hit the 20 device soft limit? You could extend that to like 50 devices in `Espalexa.cpp`.

Yes, Espalexa is based on both Fauxmo (for the SSDP discovery over UDP) as well as HUE-Emulator (or rather the Philips Hue API protocol itself). However, multiple hue bridges (which Espalexa emulates) on the same network shouldn't be an issue. My main WLED project uses 10 ESPs in my home which each emulate a hue bridge with a single device and all of them work properly. So I can't explain what we could do to fix this for Espalexa... I hope I'll be able to find a solution for you soon!

**Comment by philharlow** [comment]
I too was having this problem yesterday after taking several devices to my parent's house for Father's day, and having tested each individually, but never together.
I ended up finding the root of the issue for me late last night, and put in a workaround, but I'm not sure exactly why it's happening.
Basically, in espAlexa.cpp, the escapedMac is being set back to an empty string at some point after calling begin(). This causes the uuid and serialnumber fields in the alexa api response to be the same between every device. My "fix" was to move the escaped mac address code down to run again right before being called. Paste:

	escapedMac = WiFi.macAddress();
	escapedMac.replace(":", "");
	escapedMac.toLowerCase();

at the beginning of:

void serveDescription()
and
void Espalexa::respondToSearch()

Now the mac address is properly filled and the devices now all work together!
It may not be necessary to do that in both places, but I found the fix at 4am, and once it was working, I went to bed :)
Hope this helps!

**Comment by MopheusDG** [comment]
For me it's not working... as soon as I commented those 2 lines, the ESP boots but stops responding ping's almost immediately.

**Comment by Aircoookie** [comment]
@MopheusDG For me, the ESP doesn't stop responding almost immediately. Would you mind un-commenting line 14 in Espalexa.cpp and sending me the debug log? Then we could say at which stage your ESP fails. Good thing @philharlow 's hotfix is working for now :) Thanks again!

By the way, experimenting made my ECHO itself become unresponsive twice now, where it would first react delayed and then just have the blue ring on without reacting to "Alexa" callword!

**Comment by MopheusDG** [comment]
@Aircoookie , this is weird, this is the only debug I get:

`Constructing device 1
Adding device 1
Constructing device 2
Adding device 2
Constructing device 3
Adding device 3
Constructing device 4
Adding device 4
Constructing device 5
Adding device 5
Constructing device 6
Adding device 6
Constructing device 7
Adding device 7
Constructing device 8
Adding device 8
Constructing device 9
Adding device 9
Constructing device 10
Adding device 10
Constructing device 11
Adding device 11
Constructing device 12
Adding device 12
Constructing device 13
Adding device 13
Espalexa Begin...
Done
Got UDP!
NOTIFY * HTTP/1.1
HOST:239.255.255.250:1900
CACHE-CONTROL:max-age=16
LOCATION:http://192.168.0.254:8200/rootDesc.xml
SERVER: 3.14.77 DLNADOC/1.50 UPnP/1.0 MiniDLNA/1.1.5
NT:uuid:4d696e69-444c-164e-9d41-001075589038
USN:uuid:4d696e69-444c-164e-9d41-0
`

And it dies there.

**Comment by MopheusDG** [comment]
No problem. Thanks @AirCookie

**Comment by Aircoookie** [comment]
Ok I finally got around testing this. The crash after the first UDP message was caused by an UDP buffer array index out of bounds issue... I've updated the Github Repo, everything should work now!

**Comment by philharlow** [comment]
👍👍
Sorry I wasn't able to test yet, but I'm glad it's all working! Thanks @Aircoookie!
