### ISSUE TITLE
EspAlexa and EspAsyncWebserver duplicate declaration conflict

### ISSUE THREAD

**Issue by thehellmaker** [Aircoookie/Espalexa#16]
I am getting definition conflict when I useEspAlexa with EspAsyncWebserver

In file included from ~\.platformio\lib\Espalexa_ID5525\src/Espalexa.h:8:0,
from src\src.cpp:23:
~\.platformio\lib\Espalexa_ID5525\src/dependencies/webserver/WebServer.h:36:85: error: redeclaration of 'HTTP_OPTIONS'
enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

**Comment by thehellmaker** [comment]
In file included from ~\.platformio\lib\Espalexa_ID5525\src/Espalexa.h:8:0,
from src\src.cpp:7:
~\.platformio\lib\Espalexa_ID5525\src/dependencies/webserver/WebServer.h:36:60: note: previous declaration 'HTTPMethod HTTP_PATCH'
enum HTTPMethod { HTTP_ANY, HTTP_GET, HTTP_POST, HTTP_PUT, HTTP_PATCH, HTTP_DELETE, HTTP_OPTIONS };

**Comment by Aircoookie** [comment]
Hi, do you use ESP8266 or ESP32?
The declaration conficts is because Espalexa needs a webserver to communicate to Alexa via HTTP and you can only have one server running on the ESP. You can look at [this](https://github.com/Aircoookie/Espalexa/blob/master/examples/EspalexaWithWebServer/EspalexaWithWebServer.ino) example on how to use the regular Webserver alongside Espalexa (in fact, Espalexa will use your webserver instead of the built-in then).
AsyncWebserver is currently not supported by Espalexa. If you can't use the regular webserver for your application, I could try and make Espalexa support EspAsyncWebserver, however I can't promise that would work, though.

**Comment by thehellmaker** [comment]
I use ESP32. I need to make it work with ESPAsyncWebServer as My platforms depend on it. 
Thanks a lot for taking up the task. However since I need it I could make a pull request and fix it and send it out for a review. 
But I need some help from you to get started with the same.

**Comment by Aircoookie** [comment]
Hi, sorry that I took so long to respond.

I'm looking into creating a new branch which supports AsyncWebServer. Basically it is just swapping the two libraries and changing some syntax, but these two versions of Espalexa will (probably) not be interchangable, so having the separate branch seems like a good solution. I'll get back to you once I have something working!

**Comment by d-999** [comment]
Ok, so I'm trying to get Espalexa to use ESPAsyncWebServer instead of ESP8266WebServer, to solve the duplicate declaration conflict (pretty much as you planned on doing). After reverse engineering your library a little, I believe I almost have it working. Everything seems to be working fine. The only problem is that I now ran into the same problem that occurs with the newer ESP8266 cores where presumably the wrong content type causes no arguments to be returned from the ESPAsyncWebServer library.
Any thoughts on that? I'll try to see if the library can dump the complete request or something later on.
Anyway, for now happy new year! :-)

**Comment by d-999** [comment]
Thanks! :-)
Yeah, I'd also prefer to leave Async untouched. Especially considering there's nothing wrong with the library having trouble parsing, what is essentially a broken HTTP request. Really Amazon should fix their HTTP requests. But I've observed quite a few little glitches here and there, they don't seem to have put a whole lot of effort into Alexa's firmware.
Anyway, I'll see what I can do tomorrow without messing with the Async library itself. If everything fails, I guess we'd have to put up a modified Async version, for the Espalexa library or something.

About the color support... Wow, I can't wait to check it out. That'll definitely open a whole new range of possibilities.

**Comment by Aircoookie** [comment]
Hi again!
Since you already have the library fully working with the async server (except for the empty request body issue), could you send me your modified code? On Friday I'll have some time to play around with it and try to find a workaround.

To be honest, I agreee that most of the local hue API implementation of Alexa is a mess, but it is still way better than having nothing, which would make it impossible for hobbyists to easily voice-control their projects :)

**Comment by d-999** [comment]
Hey, yes I was planning on doing so anyway. I'm not home right now, but I'll do so later on when I'm home. Do you have any preferred way for me to send you the code? Should I fork the library or send it to you directly?

And yes, I agree. As long as we get things to work one way or another, that's definitely an achievement. Besides, it doesn't really have to be 100 % reliable. The world won't end if I have to turn my lights on manually you know. :-)

**Comment by Aircoookie** [comment]
Cool! Since I'll manually add your changes to the 2.2.0 version in a separate branch for testing, send it to me the way you prefer!

That's true! :)

**Comment by d-999** [comment]
I just realized one can send files in the comment section itself here, that's easy enough I guess...
So I have good and bad news. The good news is it appears to be working now and the bad news is I'm not quite sure why. I had inserted test strings before just to see if the code behaves as expected apart from the json problem. And now I just wanted to change it back to the "normal" not working state. Now however it seems to work just fine. That is really confusing.
Well, I guess it's possible I just screwed something up before. I did however download the lates Async version at some point since it said something about "Corrected datatype für JSON_MIMETYPE (#396)" (note the "für" in German :D), so maybe that's why it works now and didn't before? I really have no idea. I haven't spend a lot of time testing it yet, so I'm not sure it works reliably. But feel free to test it and let me know if you find any anomalies.
Here is a zip file with my changed version of the library. 
[AsyncEspalexa.zip](https://github.com/Aircoookie/Espalexa/files/2722399/AsyncEspalexa.zip)
Note that I have changed the the names of the .cpp and .h files to "AsyncEspalexa" and changed the import of Espalexa.h in the .cpp file and the EspalexaBasic example to AsyncEspalexa.h apart from that the only changes I made are the changes in .cpp and .h to make the library use Async rather than the standard Webserver library.
Therefore the "EspalexaWithWebServer" example sketch doesn't work since it imports the old library name and uses the old Webserver library. The "EspalexaNoLibrary" example  should work since it's standalone and doesn't use the actual library. But anyway, the point is, I only worked with the .ccp and .h source files and the Basic example. The rest is unchanged. Also I didn't update any of the dependencies, you'll need to install [ESPAsyncWebServer](https://github.com/me-no-dev/ESPAsyncWebServer) yourself.

**Comment by d-999** [comment]
Oh and I forgot to mention, I only worked on it with ESP8266. I didn't try, but I believe removing the conditional imports etc. for ESP8266 and ESP32 I believe it shouldn't be difficult to get it to run on ESP32 as well if you just treat the ESP8266 and ESP32 the same.

**Comment by d-999** [comment]
So in my case I decided to also use port 80 for HTTP requests to my sketch. Therefore I changed the
[EspalexaWithWebServer](https://github.com/Aircoookie/Espalexa/files/2724517/EspalexaWithWebServer.zip) example to work with the Async version of Espalexa as well. Just thought I'd upload it here as well.
Apart from that I did some testing today and there was a time where I had to discover two times, 'cause Alexa didn't find my device on the first try, but apart from that the library seems to be running fine so far. Maybe it was really just the fact that I download the latest Async version. As far as I can tell, Async has been having some trouble with JSON in general. So maybe it was just the Async library causing problems.
Maybe I'll try different versions to see if it is in fact dependent on the version running.

**Comment by Aircoookie** [comment]
Awesome work! I'm going to test your solution and then see if it's feasible to integrate in the "main" version of Espalexa or if we should keep a separate branch for the async version.

**Comment by d-999** [comment]
Yeah, I was thinking one could maybe #ifdef it so you essentially have both options in one library. Unfortunately I didn't quite think ahead while editing the library. It would have been smart to comment out the lines I changed, add new ones and maybe add a comment with a keyword in order to be able to find all the changes easier later on.
But I guess you can use difference finder. There's a plugin for notepad++ for example that lets you open two files side by side and highlight the differences.

**Comment by Aircoookie** [comment]
Hey! I just pushed 2.3.0 which has the async support!
Your work was a great help!
Interestingly, I got the "empty body issue" immediately.
However, it turns out there is a separate callback for the body content: https://github.com/me-no-dev/ESPAsyncWebServer/issues/123
With that in place it seems to work reliably for me with ESP8266 and ESP32.
Let's hope it works well for you, too!

**Comment by d-999** [comment]
Really? That is so strange... I have the code I sent you running at home right now and it works perfectly, while the link you sent was one of the many solutions I had tried that didn't work for me...
And in fact I just downloaded version 2.3.0 and tested on ESP8266 and ESP32 and I get the good old "always on" issue on both. I also tried uploading my version to the same ESP8266 just to make sure and sure enough it still works fine... So how do we debug that...?

**Comment by Aircoookie** [comment]
How strange... It might be that sometimes `onRequestBody` is called first (like for me) and sometimes `onNotFound` first (might be based on network delay or something, don't ask me). I think I can work around this issue by using both your and my method for getting the body, and then check if one is empty, if it is, use the other which then should likely contain the correct data. In my opinion that would be quite an ugly workaround, but hey, if it works...
By the way, you could confirm that "my" method doesn't work for you by doing `#define ESPALEXA_DEBUG` before `#include <Espalexa.h>` (i thought it would be helpful to be able to toggle it from the sketch!) and see whether `Received body: [json]` appears in the serial log at all. Maybe it even does work, but appears after "AlexaApiCall".

**Comment by d-999** [comment]
Hey... Yeah, I thought of that too, but also thought it's not a very elegant solution. Especially since we don't know for sure if there may be cases where both would return an empty body. I think it's quite strange that my solution works for me reliably and not just sometimes, while it never works for you and vice versa.
And good you remind me, I totally  forgot to mention, I actually did enable debugging (uncommented the define in Espalexa.h, but I guess that shouldn't make a difference) and strangely I got no "Received body:" at all... Not even an empty one. Neither on the ESP8266 and ESP32.

**Comment by Aircoookie** [comment]
There are cases where neither will return a body, like when Alexa sends `GET /api/apikey/lights/1`, that is not a problem. That you get no "received body:" doesn't surprise me since `onRequestBody` never gets called for you. If it matters, I'm using ESP8266 arduino core 2.3.0 (i know it's an old version but it has the lowest flash usage in my WLED project) and ESP32 core 1.0.0. I just pushed v2.3.1 which implements the workaround, so it should work for you now.

**Comment by d-999** [comment]
Ah ok, I didn't look at the source code yesterday, so I didn't realize you changed where the "Received Body:" is sent in the code.
I tested version 2.3.0 and it works once, but because `onRequestBody` is never called in my case every the following request's `body` contains the body from the last request and is therefore not empty and the 2nd method isn't used. Therefore after setting the brightness once, the brightness is always set to that brightness afterwards, no matter what you try to set it to. For example adding 
```
#ifdef ESPALEXA_ASYNC //necessary because body is only defined globally when Espalexa uses Async
body = "";
#endif
```
to the end of `serveNotFound()` solves the problem.
There is still a problem however. I also tried version 2.3.0 without `#define ESPALEXA_ASYNC` to see if it works correctly with the normal webserver and it does on ESP8266, on ESP32 however I get the always on issue (on Async it works fine on both and uses the 2nd body method for both in my case btw).
I've been wondering how why you and me seem to be getting different requests from Alexa using the library and I wondered if it may also be related to the Echo version. Perhaps you could try unplugging the others and use only the Echo Dot 2 to see if the 2nd body method works for you then?
If it does, maybe that also explains the color issues with the Echo Dot 2. According to google, colors should work on only the Echo Dot 2. That in combination with us apparently receiving different requests from Alexa makes me wonder if maybe the firmwares of the Echo Dot 2 and the newer Echos interact with the hue bridge slightly differently in a way that works with the original hue bridge, but not with the way Espalexa emulates the hue bridge, since I presume you've been prototyping mainly with all Echos running, which apparently causes the newer firmware to take over.

**Comment by d-999** [comment]
Oh and thanks for adding me to the contributors btw... :-)

**Comment by Aircoookie** [comment]
You're welcome!
Ah, that the body of course isn't empty anymore after the first request was a total oversight on my part... I also agree with you that the `if (body.length() == 0)` check shouldn't be necessary, so I removed it and it still works fine. Even more, I think I have worked out why:
- Different methods work for both of us
- Non-Async on ESP32 works for me, but not for you

Your assumption about our Alexas sending different requests was totally correct. It turns out that the new update did not just enable color support, but also fixed the erraneous `x-www-form-urlencoded` content type to the proper `application/json`. My Echo Dot still sends the former, while the Echo sends the correct type. So it seems that regarding the Async server, the `onRequestBody` is how it is supposed to work, and  `request->getParam("body", true)->value();` is the workaround for the wrong content type header. To verify that, I tried ESP8266 Arduino core 2.4.2 Non-Async without the Parsing.cpp workaround. Echo Dot: Always On issue as before, normal Echo: working perfectly fine.
So these are some great news, those hacky workarounds will no longer be needed once the Dot gets its update!

**Comment by d-999** [comment]
Awesome! I'm great we figured this weird behavior out. It's funny how most of our problems seem to be due to sloppy programing on Amazons side. I guess one would expect programmers that get paid for programming to work a little more "gewissenhaft" for lack of a better word.
So I guess it's just a matter of time until they push on update for the Echo Dot 2 then (hopefully).
I haven't tried version 2.3.2 yet. I'll do so later or tomorrow and let you know if I find any unusual behavior. But I expect we probably got the problem under control now. :-)
Thanks for all your work on the library, not to mention writing the library in the first place! It has definitely been very useful for me so far.
