### ISSUE TITLE
No discovery with 2.1.2

### ISSUE THREAD

**Issue by RanTalbott** [Aircoookie/Espalexa#17]
ESPAlexaBasic, Compiled for a Wemos D1 Mini with Arduino 1.8.4, ESP8266 2.3.0, and a freshly-downloaded copy of ESPAlexa. Echo Dot 2nd Gen, Android Alexa app version 1.24.203566.0

The Echo Dot was purchased last Black Friday, and has the problem of not recognizing fauxmo devices because it needs the Wemo skill to use them.

Discovery fails on both the app and the Echo. No SSDP discovery messages are being sent (I have a Linux app that watches the WiFI for them). The ESP8266 does respond correctly to an M-SEARCH broadcast from a Linux app, and returns what looks like a good description.xml.

I tried to enable the Hue skill, but that failed during account linking because I don't have a real Philips device. Is this necessary for the sketch to work?

I'm seeing the same problem with Xose's 3.0.0 version of fauxmo, which also uses the Hue protocol. Is this a result of the Alexa software changes that screwed up lots of emulators?

**Comment by Aircoookie** [comment]
That's unfortunate. Seems like Amazon changed things up again. Thanks for your detailed report! I tried to reproduce the problem and found the following (my network has 1 Echo+, 1 Echo 2 and 2 Echo Dot (2nd gen), I'm based in Germany):
- Asking the Echo 2 for discovery: M-SEARCH is send from both the Echo plus and the Echo 2, but NOT the dots. Discovery succeeds.
- Asking the Echo Dot for discovery: It sends M-SEARCH, but only from itself, not the other echos in the network. Also, it only sends it right at the end of the discovery period, which seems to make the discovery fail like 50% of the time.
- Discovery from app: All Echos send M-SEARCH. Discovery succeeds. However the Echo 2 and plus seem to send more M-SEARCH packets.

So I can partly reproduce the issue you're having in that the other Echos are more reliable with discovery than the Dots, but still the discovery works on the dots somehow.

What country do you use the Echo dot in? It may be a region-limited issue, or it only affects a certain batch of units.
If your Echo doesn't send any SSDP M-SEARCH broadcasts, Espalexa obviously can't respond to the discovery and therefore it fails.

The Hue app/skill is neither necessary nor supported since it uses online servers for communication and is not local like the combination of SSDP + hue local API which we use.

I'm sorry, but there is nothing I can do currently to help or fix this. This is just speculation, but I guess Amazon will stop supporting local devices entirely someday in favor of the hobbyist-unachievable vendor cloud services.

**Comment by RanTalbott** [comment]
Thanks for the reply and info. I'm in the U.S., and bought the Dot from Best Buy, so we can be pretty confident that it's a U.S.  model that was from a very recent batch at the time. If you think it might be significant, I'll go back and re-learn the pagan ritual that lets you find out the firmware version of the Dot. I'm pretty sure (but not absolutely) that it's been auto-updating itself to the latest release.

Confirming that I don't need the Hue skill was a big help. It's not clear whether you need the skill, and Alexa keeps encouraging the user to enable it, so it might be beneficial to include the fact that you don't in the docs.

One other thing that that might be useful to others experiencing problems: I've never used Wireshark on WIFi before, and it looked to me like it wasn't capturing everything like it does on Ethernet, even though I told it to set "promiscuous mode". It doesn't: you also have to use iwconfig to set "monitor mode" on the WiFi, and the driver for my USB WiFi dongle doesn't support it. So I missed some traffic when I was trying to get the details of what was going on, because I was only getting broadcasts and packets going to/from my PC.

Thanks again,

Ran
