### ISSUE TITLE
Interference with IRremote Library on ESP8266

### ISSUE THREAD

**Issue by bchwtz** [Aircoookie/Espalexa#2]
Hi Aircookie,
nice work - your script works like a charm, right out of the box and stable with 5+ devices. I tried a few things with the IRremote Library for ESP8266 (https://github.com/markszabo/IRremoteESP8266) but could not get it to work. It seems that the pins are not controlled properly. All examples from the IR library work without problems (tested on Wemos D1 mini) and problems only occur in conjunction with the Espalexa script. Do you have any ideas why that is the case and how to fix it?

Thanks for the good work.
bchwtz

**Comment by Aircoookie** [comment]
Hi @bchwtz,

thank you for trying out the script! I'm glad you like it!
At the moment I can think of no apparent reason for why the IR library and Espalexa shouldn't work together...
Sadly I can't try it out myself since I don't have an IR led/receiver. It would help me a lot if you could open a Github Gist with your code (I assume you have added the IR library functions from the examples into the setup() and loop() functions of the sketch) to see if I can find anything that may cause your issue.
As for espalexa itself, it uses no hardware functions like interrupts or I2S which the IR library may require. The only thing it uses is a Serial port for debug. You may want to try and remove all Serial.begin() and print() functions, however I doubt that will fix anything. Another possible workaround would be to use different pins for the IR sensor.
I'm sorry that I was not able to find the problem yet, but I am sure we can find a solution!
Aircoookie

**Comment by bchwtz** [comment]
Hi @Aircoookie,
thank you for your fast response. I went through the code again and just forgot a begin() command which then caused the weird behaviour of the pins. This obviously wasn't connected to your code. Sorry for the trouble. If you need someone to test the library release you are working on... just let me know. I am really looking forward to it.
bchwtz
