### ISSUE TITLE
Encapsulate it as a library

### ISSUE THREAD

**Issue by xoseperez** [Aircoookie/Espalexa#3]
Have you thought about creating a library with the minimum code necessary to add it to other projects?

**Comment by Aircoookie** [comment]
Yes, in fact I am already working on it. At the moment i am quite busy though so it might take 1-2 weeks until the library is finished. Stay tuned and thanks for being interested in the project!

**Comment by bchwtz** [comment]
I also would love to see a library release that targets the following:

- More convenient and compact device definition. Probably in the form as the Belkin WeMo emulators do: `device = new WemoSwitch("friendly Name", 80, onFunction, offFunction);`
- Optional definition of non-dimmable devices, e.g. switches
- Selectable Range for dimmable devices. 

Thanks and keep up the good work!
bchwtz

**Comment by Aircoookie** [comment]
Today I resumed working on the library.
@bchwtz 
- Device definition will be very similar to what you suggested. You can either do: `espalexa.addDevice("name", onFunction, offFunction)`
or this:
`EspalexaDevice d = new EspalexaDevice("name", onFunction, offFunction);
espalexa.addDevice(d);`
The former just creates the device object internally, which is easier to use.
However, the latter has the advantage that you can access the device object to do stuff like `d.setValue(128)`. This can be useful if you like to also change the device state with a physical switch or web interface.
- You will be able to declare your ON callback function either without parameters or with one `uint8_t` .
If you have the parameter, it will include the brightness. So, if you don't need brightness control for a device, just define the on function without parameters.
- Since the underlying Hue protocol only allows brightness control in the 0-254 range and Alexa can only control in 5% steps, selectable range is not needed IMO. The 8bit value will be enough. If you require a different range, you can of course just use the Arduino `map()` function.

👍

**Comment by xoseperez** [comment]
Just one suggestion: wouldn't it be better to have just on callback function with status and brightness as parameters? I think it's simpler.

**Comment by Aircoookie** [comment]
Great idea! I'll keep the on/off functions for those who look for a replacement for the Wemo library but also add another constructor that allows for only one callback function 💯

**Comment by bchwtz** [comment]
Ich strongly support YouTube opinion @xoseperez. If there is no internal handling and the switches appear dimmable in the App even If they are Not, there is no real Point for aiming to reproduce the WeMo emulators. In thus Case ist IS definitely 💯 perfect to habe only one callback function with 2 parameters.

**Comment by Aircoookie** [comment]
Library is up and working, tested on ESP8266 and ESP32 with 20 emulated devices each successfully!

Because there is only the one brightness value (0-255) I've decided to only have one callback function with this one parameter per device, like you suggested. When only on and off is needed you can of course just treat the `uint8_t` as a `bool`.

I've added the documentation to the readme and also some examples.

Enjoy and please report back if you run into any issues using the library!
