### ISSUE TITLE
Device doesn't respond (according to Alexa)...?

### ISSUE THREAD

**Issue by d-999** [Aircoookie/Espalexa#69]
Hey there, so I'm not sure this is an issue with the library, it may be an issue with my code. But anyway, I've been experiencing some problems lately where Alexa says the device doesn't respond and for me to check the power and network connection. What is interesting is that this problem doesn't always occur and when it occurs the device does still react to Alexa. If I tell Alexa to dim the light to 50 %, she says the light doesn't respond but the light dims to 50 % anyway. It takes 5 seconds or so for Alexa to say that though and the light only dims when Alexa says the device doesn't respond (so it takes longer than usual).
Anyway ... I'm using AsyncWebServer and my code also uses the Webserver used by Espalexa. At first I thought something may be blocking the main loop and `espalexa.loop();` may not be called often enough. And interestingly this problem does seem to occur less often when there is less going on in the main loop. But even with only `espalexa.loop();` in the main loop this problem still occurs. Apart from that I wondered if my code using the Webserver may have anything to do with it. But I don't think that's the case since Alexa doesn't call the paths of the Webserver in my code. I was wondering if this may have anything to do with the new firmware for the Echo Dot 2 since this problem just sort of started occuring for some reason even though it didn't occur before. But I don't know exactly when the Echo Dot updated. I'm using an Echo Dot 2 (Germany, firmware version 635560020).
I didn't really have the time to investigate this further and unfortunately it's kinda difficult to debug since it's one of these things that occur fairly randomly (about 10 % of the time) but magically seems to never occur when you want it to. :-) I'll let you know if I find more out about when/why this occurs. But in the meantime I thought maybe you have an idea what could be causing this or under exactly which circumstances Alexa says the device doesn't respond?
Sorry for the long message, I wanted to try and describe the problem as accurately as possible. Hope my explanation helps or maybe someone can reproduce the problem?!

**Comment by Aircoookie** [comment]
Hey again, thank you for the detaiked problem description! I've also experienced this issue before. Probably it is an issue with WiFi modem sleep, where the ESP somehow doesn't receive the first command. The Echo then waits 5 seconds, sends the command again (that time it will work and turn the device on), but immeadiately says the device is unreacheble.

I believe this primarily happens when the device was not toggled for a longer time.
Very interesting to know that it seems to happen more frequently when there is more going on in your application! You may try using `yield();` here and there, it will give the WiFi libraries time to operate and any incoming Alexa command will immediately be handled.

I'll keep an eye out, maybe I can somehow reproduce how this occurs. I know it is quite annoying, because Alexa keeps talking for half a minute about the device being offline!

**Comment by Aircoookie** [comment]
In fact, calling `espalexa.loop()` more often won't help at all, since that only processes the UDP (device discovery) packets. The asyncwebserver is processed every time the main loop exits or `yield()` is called :)

**Comment by d-999** [comment]
Hey thanks for info on this...
Now where I think of it. You're absolutely right, everything happens in the `espalexa.handleAlexaApiCall(request)` not `espalexa.loop()`. Hmm... I wonder if running more stuff in the main loop causes the webserver to "lose" requests or something? I can't imagine that being the case since my main loop isn't very demanding on the processor. Maybe it was just coincidence that it happened less once I commented out the stuff in the main loop. It's kinda impossible to tell since this issue happens quite randomly anyway.
Unfortunately I can't use yield() since I'm using AsyncWebServer and they don't get along (as stated [here](https://github.com/me-no-dev/ESPAsyncWebServer#important-things-to-remember)), actually I'm not sure that applies to the main loop, isn't yield called at the end of the main loop anyway? But I don't think it's gonna help much given that the problem even occurs with an empty main loop.
Also, I have had this occurring two times or so in a row (within like 10 seconds), so it also happens sometimes when the device was toggled recently.
What is interesting to me is that this problem started occurring fairly often lately while not happening at all before. It has even started occurring on a device using the fauxmo library. So I guess it may somehow have something to do with the a firmware update for the Echo Dot 2. But in either case I think it's worth investigating, since (as you said) it can be quite annoying when you wanna quickly turn something on/off and Alexa goes on and on about how the device doesn't respond.

**Comment by Aircoookie** [comment]
That is interesting! If it only started happening recently and also happens with fauxmo, then it wouldn't surprise me if this was a bug on the Echo side again (there are some, including the one making the content type workaround neccessary). However, we can't conclude that quickly, because there may be an ESP wifi library or Espalexa issue which only became apparent after the Echo update (fauxmo derived some parts of their code from Espalexa). Maybe I have time later to try and reproduce as well as do a network scan. It would be interesting to know if Alexa actually sends the control packet (or if the first packet sent by the Echo is at the same time as the "Device doesn't respond" message)

You may in fact use `yield()` in the main loop, it can help with various wifi related issues (but as you said, only if there is a lot going on in the loop). It is correct that `yield()` does cause issues if called from the system context, not the applications context. Sounds complicated, but basically means that you can absolutely use it in the main loop and methods called by it, jsut that you can never use it in async callbacks (webserver handlers or Espalexa `onDeviceChanged()` functions) or interrupts.

**Comment by d-999** [comment]
Hey there, unfortunately I haven't had much time to investigate so far. I only really found that `espalexa.handleAlexaApiCall(request)` was being called and returned true twice about 200 ms apart on successful attempts to set something and three times around 30-90 ms apart on failed attempts (where Alexa reported the device isn't responding), I haven't captured contents of the requests yet though. Also, I'm not using the latest version, I don't really expect updating to change much, but I'll try and let you know if it makes a difference. Most importantly however, this started happening frequently at a time where I changed quite a lot at once and so I didn't immediately associate it with this, but I've found that this only happens on ESPs running ArduinoOTA. I first didn't associate it with that, since I removed all kinds of things including OTA from them main loop (or made them conditional). But even if they are not always called in the main loop, `ArduinoOTA.begin()` is obviously still being called in the setup and so the library is running. As far as I can tell though it really seems to only occur (on Espalexa and fauxmo) when ArduinoOTA is running, so I believe they are conflicting with each other in one way or another. I'm still planning on trying to capture the data being sent, but unfortunately I currently don't have so much time and for some reason this problem seems to mainly occur when I'm not trying to debug it.
Anyway, maybe you can reproduce this issue using ArduinoOTA (if and when you have time to work on it).

**Comment by d-999** [comment]
Ok, so I haven't really put a lot of effort into fixing the problem, recently I changed the code to call `ArduinoOTA.begin()` when a certain URL is called, so that OTA is normally not running, but can be manually started in order to upload a sketch.
Espalexa however is still not quite working as it should. I'm not sure if this is the same problem as before. But it started getting significantly worse a lately. Also now Alexa says different things. When I try to change the state of a device using Alexa, one of the following things happens:
She says ok
After a few seconds she says "<device name> scheint nicht richtig zu funktionieren"
After a few seconds she says "<device name> antwortet nicht ..." and tells me to check the power and network connections.
Most of the time the state of the device is successfully changed though. Also all Espalexa devices in Alexa are shown as "Royal Philips Electronics intelligentes Gerät" now and Fauxmo devices are shown as "Belkin International Inc. intelligentes Gerät" which makes me wonder if an update for Alexa may have caused these problems, since they seem to occur now with and without OTA running.
Have you experienced any similar problems yet?

**Comment by d-999** [comment]
Ok, so for some reason the "_device name_ antwortet nicht" happened the first few times after OTA wasn't running anymore, but now it doesn't anymore. And the "_device name_ scheint nicht richtig zu funktionieren" always happens when turning a device off or to a certain brightness (not when turning it on) and it doesn't happen for all devices. I believe it is a problem with my own code though, I'll have to investigate that when I have time...
In any case the "device doesn't respond" issue seems to be a compatibility issue between Espalexa and the OTA library and not directly a problem with Espalexa therefore I will close this issue.
And if the problems I am currently having seem to be a problem of Espalexa after all, I'll open a new issue for it since I doubt it isn't related to this.
