### ISSUE TITLE
2 ESP32 in same network trouble

### ISSUE THREAD

**Issue by maxxmazz** [Aircoookie/Espalexa#71]
Hi
I have a ESP32 Dev Module programmed with one device in Espalexa and working fine
When I upload on second module the base example and discover in alexa the first module stop working, I continue to see in alexa all the device but when I try to use the command goes to first device in second module.
Just deleting the device of the second module and the first is working fine.

Thank you and sorry for my bad english

**Comment by Aircoookie** [comment]
That is a weird issue. Have you given the devices different names? If they both have the same name, one will overwrite the other.

**Comment by maxxmazz** [comment]
The virtual device in the sketch have different name, I don't know how to give different name at ech ESP32 board. In the app I can see all the device when discovered. The IP are different and the mac address are different in the last 5 character. The only strange things I saw is on the router: one module is recognized as expressif the other one is unknow

**Comment by MopheusDG** [comment]
I started having this problem too now, but on ESP8266. Maybe something Amazon changed ?

**Comment by MopheusDG** [comment]
This is my example:

ESP #1 

> 
Hello from Espalexa!

Value of device 1 (TV): 0 (Dimmable light)
Value of device 2 (Amplificador): 0 (Dimmable light)
Value of device 3 (Aire Acondicionado): 0 (Dimmable light)
Value of device 4 (Luz del BalcÃ³n): 0 (Color light, colormode=xy, r=254, g=221, b=80, ct=500, hue=0, sat=0, x=0.50, y=0.50)
Value of device 5 (Computadora): 0 (Dimmable light)

Free Heap: 36536
Uptime: 5270539

Espalexa library v2.4.1 by Christian Schwinne 2019
> 

ESP #2
> 
Hello from Espalexa!

Value of device 1 (Proyector): 0 (Dimmable light)
Value of device 2 (Adorno): 0 (Color light, colormode=xy, r=254, g=221, b=80, ct=500, hue=0, sat=0, x=0.50, y=0.50)

Free Heap: 37024
Uptime: 12747171

Espalexa library v2.4.1 by Christian Schwinne 2019
>

**Comment by roffey** [comment]
Although I'm not using this actual library... only just come across it.... I had four esp32 units controlling multiple devices, blinds, lights, rf etc  working fine for the last 9 months. Few days ago it all went crazy...  devices either not controllable or controlled by other device names etc. Tried everything... deleting all.. re discovering etc...   definitely something with Alexa going on.. update? 
Now am setting up one esp32 with 24 devices.. all found and responding.. so am udp'ing from this central unit to my other controls..  only one unit to worry about.. and will incorporate artnet etc

**Comment by jemarr** [comment]
Same problem since two days ago... Amazon has changed something.

I tried Fauxmo lib as well with same issue.

I have three ESP8266 boards with 1, 2 and 4 devices each. The last discovered devices board is which Alexa takes as 1st, 2nd.... device on Routines and Groups, doesn't matter the device name.

When you call by voice all devices runs well, the problem is just with Groups and Routines.

Any thoughts ???

**Comment by roffey** [comment]
Yes, they've messed up somewhere. I have got all my stuff working again by having one esp dealing with 24 devices, then sending out udp to my other esp units, instead  of multiple fauxmos. Noticed that changing device name in devices works fine, but this change is not always reflected in the routines and displays the original device name. Someone has messed up.

**Comment by roffey** [comment]
Yes, they've messed up somewhere. I have got all my stuff working again by having one esp dealing with 24 devices, then sending out udp to my other esp units, instead  of multiple fauxmos. Noticed that changing device name in devices works fine, but this change is not always reflected in the routines and displays the original device name. Someone has messed up.

**Comment by roffey** [comment]
I also see Alexa responds to device new name and its start out name. It won't delete correctly. I assume someone has done some upgrade and not bothered to check it properly before implementing it.

**Comment by SpiderIncognito** [comment]
Hello, il have the same issue since two days, probably Alexa firmware update...
I have multiple ESP8266WiFi each with own espalexa routines...
The last registered on Alexa Works with routines not the others....
For now my only way it’s to program « the lord of Alexa » who.s manage this other and send them orders..
Hopes that this helpfull library Will update to solve this issue.

**Comment by MopheusDG** [comment]
I've also seen that my original HUE is getting confused with our ESPAlexa library... sometime I set a device to 100% and one of my Philips lamps is powering up instead the ESPAlexa device :S

**Comment by roffey** [comment]
To my mind it must be to do with the uniqueness of the data sent back in response to the device search when the separate esp's are being deployed. There must now be further data used in the identification process in determining exactly what device gets communicated with when an alexa command is issued.
This will be in the 'reply' to a device search... exactly what though, I don't know.

The phillips hub controls linked lights via rf, and as such is only one communication path.. Be interesting to know if users with multiple hubs have the same issue. As such these hub devices have to be selected individually for use in the phillips app in order to activate linked lights.

I am now much happier having my 5 or so esp's controlled via my 'master' alexa link. All up and running, back to where I was, running scheduled routines, theme routines etc. 
The master has 24 device slots, and controls a few rf lights along with sending the same alexa commands out via UDP. The other esp's listen on the same UDP port and respond accordingly. 
Really easy to add more esp's without the hassle of device search etc, and also has helped with themes, where I previously had to add short delays between actions (using alexa speech), to prevent missed device switch ons.
I would advise noting any original device name, along with any name change given to that device name.
My name change appears in the device list, but ...... not all name changes appear in the list used when setting up routines, where the original device name can still appear.

**Comment by clabnet** [comment]
Me too. Only for tracKing thread.

**Comment by jemarr** [comment]
With Tasmota they have found a solution. What they do to solve the issue is to assign a unique LightId for each device based on the iP adress or MAC adress of the esp8266 board.

https://github.com/arendst/Sonoff-Tasmota/pull/5890#issue-283790733

Is it possible to do the same with Espalexa ???

**Comment by Aircoookie** [comment]
@jemarr Thank you, it indeed seems like this new update discards the mac address part of the lightid and confuses multiple devices, which are all named "01", "02", ... for each ESP. I will try and implement the tasmota workaround. They are correct in that this may cause issues if the ESP changes IPs (most routers asssign the same IP each DHCP request though)

**Comment by MopheusDG** [comment]
Maybe just add a parameter when creating ? lightId ?

**Comment by Aircoookie** [comment]
I've just releases v2.4.3 which should fix this!
Groups and app control seem to work again now.
It is once again required to delete all Espalexa devices, and then rediscover them.

Let me know if there are any issues!

**Comment by MopheusDG** [comment]
Works for me. Thanks @Aircoookie

**Comment by SpiderIncognito** [comment]
Hello Aircoookie,

I program again all my arduino with your last release, all works fine
Thanks a lot.

Regards

Envoyé de mon iPad

**Comment by maxxmazz** [comment]
Tested and now all works fine
Thank you Aircoookie
